# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1503, 876)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #353535;\n"
"}\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    margin: 5px;\n"
"    padding-top: 10px;\n"
"    color: white;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #666;\n"
"    color: #999;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #999;\n"
"    height: 8px;\n"
"    background: #333;\n"
"    margin: 2px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #4CAF50;\n"
"    border: 1px solid #4CAF50;\n"
"    width: 18px;\n"
"    margin: -2px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"QProgressBar {\n"
"    border: 2px solid #555;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    color: white;\n"
"    background-color: #333;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #4CAF50;\n"
"    border-radius: 3px;\n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"QScrollArea {\n"
"    border: 1px solid #555;\n"
"    background-color: #333;\n"
"}\n"
"QCheckBox {\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #555;\n"
"    background-color: #333;\n"
"    border-radius: 3px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: #4CAF50;\n"
"    border-radius: 3px;\n"
"}\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QTextEdit {\n"
"    background-color: #2c3e50;\n"
"    color: #ecf0f1;\n"
"    border: 1px solid #34495e;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QWidget(self.centralwidget)
        self.leftPanel.setMaximumSize(QtCore.QSize(350, 16777215))
        self.leftPanel.setObjectName("leftPanel")
        self.leftPanelLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftPanelLayout.setObjectName("leftPanelLayout")
        self.filesGroup = QtWidgets.QGroupBox(self.leftPanel)
        self.filesGroup.setObjectName("filesGroup")
        self.filesLayout = QtWidgets.QVBoxLayout(self.filesGroup)
        self.filesLayout.setObjectName("filesLayout")
        self.modelBtn = QtWidgets.QPushButton(self.filesGroup)
        self.modelBtn.setObjectName("modelBtn")
        self.filesLayout.addWidget(self.modelBtn)
        self.modelLabel = QtWidgets.QLabel(self.filesGroup)
        self.modelLabel.setWordWrap(True)
        self.modelLabel.setObjectName("modelLabel")
        self.filesLayout.addWidget(self.modelLabel)
        self.videoBtn = QtWidgets.QPushButton(self.filesGroup)
        self.videoBtn.setObjectName("videoBtn")
        self.filesLayout.addWidget(self.videoBtn)
        self.videoLabel = QtWidgets.QLabel(self.filesGroup)
        self.videoLabel.setWordWrap(True)
        self.videoLabel.setObjectName("videoLabel")
        self.filesLayout.addWidget(self.videoLabel)
        self.outputBtn = QtWidgets.QPushButton(self.filesGroup)
        self.outputBtn.setObjectName("outputBtn")
        self.filesLayout.addWidget(self.outputBtn)
        self.outputLabel = QtWidgets.QLabel(self.filesGroup)
        self.outputLabel.setWordWrap(True)
        self.outputLabel.setObjectName("outputLabel")
        self.filesLayout.addWidget(self.outputLabel)
        self.leftPanelLayout.addWidget(self.filesGroup)
        self.settingsGroup = QtWidgets.QGroupBox(self.leftPanel)
        self.settingsGroup.setObjectName("settingsGroup")
        self.settingsLayout = QtWidgets.QGridLayout(self.settingsGroup)
        self.settingsLayout.setObjectName("settingsLayout")
        self.confLabelText = QtWidgets.QLabel(self.settingsGroup)
        self.confLabelText.setObjectName("confLabelText")
        self.settingsLayout.addWidget(self.confLabelText, 0, 0, 1, 1)
        self.confSlider = QtWidgets.QSlider(self.settingsGroup)
        self.confSlider.setMinimum(1)
        self.confSlider.setMaximum(100)
        self.confSlider.setProperty("value", 25)
        self.confSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider.setObjectName("confSlider")
        self.settingsLayout.addWidget(self.confSlider, 0, 1, 1, 1)
        self.confLabel = QtWidgets.QLabel(self.settingsGroup)
        self.confLabel.setObjectName("confLabel")
        self.settingsLayout.addWidget(self.confLabel, 0, 2, 1, 1)
        self.iouLabelText = QtWidgets.QLabel(self.settingsGroup)
        self.iouLabelText.setObjectName("iouLabelText")
        self.settingsLayout.addWidget(self.iouLabelText, 1, 0, 1, 1)
        self.iouSlider = QtWidgets.QSlider(self.settingsGroup)
        self.iouSlider.setMinimum(1)
        self.iouSlider.setMaximum(100)
        self.iouSlider.setProperty("value", 45)
        self.iouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider.setObjectName("iouSlider")
        self.settingsLayout.addWidget(self.iouSlider, 1, 1, 1, 1)
        self.iouLabel = QtWidgets.QLabel(self.settingsGroup)
        self.iouLabel.setObjectName("iouLabel")
        self.settingsLayout.addWidget(self.iouLabel, 1, 2, 1, 1)
        self.fontLabelText = QtWidgets.QLabel(self.settingsGroup)
        self.fontLabelText.setObjectName("fontLabelText")
        self.settingsLayout.addWidget(self.fontLabelText, 2, 0, 1, 1)
        self.fontSlider = QtWidgets.QSlider(self.settingsGroup)
        self.fontSlider.setMinimum(5)
        self.fontSlider.setMaximum(50)
        self.fontSlider.setProperty("value", 15)
        self.fontSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fontSlider.setObjectName("fontSlider")
        self.settingsLayout.addWidget(self.fontSlider, 2, 1, 1, 1)
        self.fontLabel = QtWidgets.QLabel(self.settingsGroup)
        self.fontLabel.setObjectName("fontLabel")
        self.settingsLayout.addWidget(self.fontLabel, 2, 2, 1, 1)
        self.thicknessLabelText = QtWidgets.QLabel(self.settingsGroup)
        self.thicknessLabelText.setObjectName("thicknessLabelText")
        self.settingsLayout.addWidget(self.thicknessLabelText, 3, 0, 1, 1)
        self.thicknessSlider = QtWidgets.QSlider(self.settingsGroup)
        self.thicknessSlider.setMinimum(1)
        self.thicknessSlider.setMaximum(10)
        self.thicknessSlider.setProperty("value", 3)
        self.thicknessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thicknessSlider.setObjectName("thicknessSlider")
        self.settingsLayout.addWidget(self.thicknessSlider, 3, 1, 1, 1)
        self.thicknessLabel = QtWidgets.QLabel(self.settingsGroup)
        self.thicknessLabel.setObjectName("thicknessLabel")
        self.settingsLayout.addWidget(self.thicknessLabel, 3, 2, 1, 1)
        self.rotateMovCheckbox = QtWidgets.QCheckBox(self.settingsGroup)
        self.rotateMovCheckbox.setChecked(True)
        self.rotateMovCheckbox.setObjectName("rotateMovCheckbox")
        self.settingsLayout.addWidget(self.rotateMovCheckbox, 4, 0, 1, 3)
        self.leftPanelLayout.addWidget(self.settingsGroup)
        self.controlGroup = QtWidgets.QGroupBox(self.leftPanel)
        self.controlGroup.setObjectName("controlGroup")
        self.controlLayout = QtWidgets.QVBoxLayout(self.controlGroup)
        self.controlLayout.setObjectName("controlLayout")
        self.startBtn = QtWidgets.QPushButton(self.controlGroup)
        self.startBtn.setObjectName("startBtn")
        self.controlLayout.addWidget(self.startBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.controlGroup)
        self.pauseBtn.setEnabled(False)
        self.pauseBtn.setObjectName("pauseBtn")
        self.controlLayout.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.controlGroup)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName("stopBtn")
        self.controlLayout.addWidget(self.stopBtn)
        self.progressBar = QtWidgets.QProgressBar(self.controlGroup)
        self.progressBar.setObjectName("progressBar")
        self.controlLayout.addWidget(self.progressBar)
        self.leftPanelLayout.addWidget(self.controlGroup)
        self.statusLabel = QtWidgets.QLabel(self.leftPanel)
        self.statusLabel.setObjectName("statusLabel")
        self.leftPanelLayout.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.leftPanelLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.leftPanel)
        self.centerPanel = QtWidgets.QWidget(self.centralwidget)
        self.centerPanel.setObjectName("centerPanel")
        self.centerPanelLayout = QtWidgets.QVBoxLayout(self.centerPanel)
        self.centerPanelLayout.setObjectName("centerPanelLayout")
        self.videoTitle = QtWidgets.QLabel(self.centerPanel)
        self.videoTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.videoTitle.setObjectName("videoTitle")
        self.centerPanelLayout.addWidget(self.videoTitle)
        self.videoScrollArea = QtWidgets.QScrollArea(self.centerPanel)
        self.videoScrollArea.setWidgetResizable(True)
        self.videoScrollArea.setObjectName("videoScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 703, 752))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setObjectName("scrollLayout")
        self.videoDisplay = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.videoDisplay.setMinimumSize(QtCore.QSize(640, 480))
        self.videoDisplay.setStyleSheet("border: 1px solid black; background: black;")
        self.videoDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.videoDisplay.setObjectName("videoDisplay")
        self.scrollLayout.addWidget(self.videoDisplay)
        self.videoScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.centerPanelLayout.addWidget(self.videoScrollArea)
        self.horizontalLayout.addWidget(self.centerPanel)
        self.rightPanel = QtWidgets.QWidget(self.centralwidget)
        self.rightPanel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.rightPanel.setObjectName("rightPanel")
        self.rightPanelLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightPanelLayout.setObjectName("rightPanelLayout")
        self.statsTitle = QtWidgets.QLabel(self.rightPanel)
        self.statsTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.statsTitle.setObjectName("statsTitle")
        self.rightPanelLayout.addWidget(self.statsTitle)
        self.statisticsText = QtWidgets.QTextEdit(self.rightPanel)
        self.statisticsText.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.statisticsText.setFont(font)
        self.statisticsText.setReadOnly(True)
        self.statisticsText.setObjectName("statisticsText")
        self.rightPanelLayout.addWidget(self.statisticsText)
        self.statsButtonsLayout = QtWidgets.QHBoxLayout()
        self.statsButtonsLayout.setObjectName("statsButtonsLayout")
        self.clearStatsBtn = QtWidgets.QPushButton(self.rightPanel)
        self.clearStatsBtn.setObjectName("clearStatsBtn")
        self.statsButtonsLayout.addWidget(self.clearStatsBtn)
        self.saveStatsBtn = QtWidgets.QPushButton(self.rightPanel)
        self.saveStatsBtn.setObjectName("saveStatsBtn")
        self.statsButtonsLayout.addWidget(self.saveStatsBtn)
        self.rightPanelLayout.addLayout(self.statsButtonsLayout)
        self.modelInfoGroup = QtWidgets.QGroupBox(self.rightPanel)
        self.modelInfoGroup.setObjectName("modelInfoGroup")
        self.modelInfoLayout = QtWidgets.QVBoxLayout(self.modelInfoGroup)
        self.modelInfoLayout.setObjectName("modelInfoLayout")
        self.modelInfoText = QtWidgets.QTextEdit(self.modelInfoGroup)
        self.modelInfoText.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.modelInfoText.setFont(font)
        self.modelInfoText.setReadOnly(True)
        self.modelInfoText.setObjectName("modelInfoText")
        self.modelInfoLayout.addWidget(self.modelInfoText)
        self.rightPanelLayout.addWidget(self.modelInfoGroup)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.rightPanelLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.rightPanel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1503, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuClasses = QtWidgets.QMenu(self.menubar)
        self.menuClasses.setObjectName("menuClasses")
        self.menuStatistics = QtWidgets.QMenu(self.menubar)
        self.menuStatistics.setObjectName("menuStatistics")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenModel = QtWidgets.QAction(MainWindow)
        self.actionOpenModel.setObjectName("actionOpenModel")
        self.actionOpenVideo = QtWidgets.QAction(MainWindow)
        self.actionOpenVideo.setObjectName("actionOpenVideo")
        self.actionLoadYaml = QtWidgets.QAction(MainWindow)
        self.actionLoadYaml.setObjectName("actionLoadYaml")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionShowAllClasses = QtWidgets.QAction(MainWindow)
        self.actionShowAllClasses.setObjectName("actionShowAllClasses")
        self.actionClearStats = QtWidgets.QAction(MainWindow)
        self.actionClearStats.setObjectName("actionClearStats")
        self.actionSaveStats = QtWidgets.QAction(MainWindow)
        self.actionSaveStats.setObjectName("actionSaveStats")
        self.actionRotateMov = QtWidgets.QAction(MainWindow)
        self.actionRotateMov.setCheckable(True)
        self.actionRotateMov.setChecked(True)
        self.actionRotateMov.setObjectName("actionRotateMov")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpenModel)
        self.menuFile.addAction(self.actionOpenVideo)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadYaml)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuClasses.addAction(self.actionShowAllClasses)
        self.menuStatistics.addAction(self.actionClearStats)
        self.menuStatistics.addAction(self.actionSaveStats)
        self.menuSettings.addAction(self.actionRotateMov)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuClasses.menuAction())
        self.menubar.addAction(self.menuStatistics.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YOLO Video Detector"))
        self.filesGroup.setTitle(_translate("MainWindow", "Файлы"))
        self.modelBtn.setText(_translate("MainWindow", "Выбрать модель YOLO"))
        self.modelLabel.setText(_translate("MainWindow", "Модель не выбрана"))
        self.videoBtn.setText(_translate("MainWindow", "Выбрать видео"))
        self.videoLabel.setText(_translate("MainWindow", "Видео не выбрано"))
        self.outputBtn.setText(_translate("MainWindow", "Выбрать выходной файл"))
        self.outputLabel.setText(_translate("MainWindow", "Выходной файл не выбран"))
        self.settingsGroup.setTitle(_translate("MainWindow", "Настройки детекции"))
        self.confLabelText.setText(_translate("MainWindow", "Уверенность:"))
        self.confLabel.setText(_translate("MainWindow", "0.25"))
        self.iouLabelText.setText(_translate("MainWindow", "IoU:"))
        self.iouLabel.setText(_translate("MainWindow", "0.45"))
        self.fontLabelText.setText(_translate("MainWindow", "Размер шрифта:"))
        self.fontLabel.setText(_translate("MainWindow", "1.5"))
        self.thicknessLabelText.setText(_translate("MainWindow", "Толщина линий:"))
        self.thicknessLabel.setText(_translate("MainWindow", "3"))
        self.rotateMovCheckbox.setText(_translate("MainWindow", "Поворачивать MOV файлы на 90°"))
        self.controlGroup.setTitle(_translate("MainWindow", "Управление"))
        self.startBtn.setText(_translate("MainWindow", "▶️ Начать обработку"))
        self.pauseBtn.setText(_translate("MainWindow", "⏸️ Пауза"))
        self.stopBtn.setText(_translate("MainWindow", "⏹️ Остановить"))
        self.statusLabel.setText(_translate("MainWindow", "Готов к работе"))
        self.videoTitle.setText(_translate("MainWindow", "<h3>📹 Обработка видео</h3>"))
        self.videoDisplay.setText(_translate("MainWindow", "Видео будет отображаться здесь"))
        self.statsTitle.setText(_translate("MainWindow", "<h3>📊 Статистика детекций</h3>"))
        self.statisticsText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">📊 СТАТИСТИКА ДЕТЕКЦИЙ НА СТОЛЕ</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">🔄 Ожидание начала обработки...</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">📈 Здесь будет отображаться:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">  • Общее количество объектов</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">  • Группировка по категориям</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">  • Уровни уверенности</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">  • Детализация по классам</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Consolas\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\';\">💡 Запустите обработку видео для получения статистики</span></p></body></html>"))
        self.clearStatsBtn.setText(_translate("MainWindow", "🗑️ Очистить"))
        self.saveStatsBtn.setText(_translate("MainWindow", "💾 Сохранить"))
        self.modelInfoGroup.setTitle(_translate("MainWindow", "📋 Информация о модели"))
        self.modelInfoText.setPlainText(_translate("MainWindow", "Модель не загружена"))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuClasses.setTitle(_translate("MainWindow", "Классы"))
        self.menuStatistics.setTitle(_translate("MainWindow", "Статистика"))
        self.menuSettings.setTitle(_translate("MainWindow", "Настройки"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.actionOpenModel.setText(_translate("MainWindow", "Открыть модель"))
        self.actionOpenModel.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpenVideo.setText(_translate("MainWindow", "Открыть видео"))
        self.actionOpenVideo.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionLoadYaml.setText(_translate("MainWindow", "Загрузить классы из YAML"))
        self.actionLoadYaml.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionShowAllClasses.setText(_translate("MainWindow", "Показать все классы"))
        self.actionShowAllClasses.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionClearStats.setText(_translate("MainWindow", "Очистить статистику"))
        self.actionSaveStats.setText(_translate("MainWindow", "Сохранить статистику"))
        self.actionSaveStats.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRotateMov.setText(_translate("MainWindow", "Поворачивать MOV файлы"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
